* Introduction

One important lesson we will learn is that where politics are concerned, **ideology**, **nationality**, and
**culture** don’t matter all that much.
The sooner we learn not to think or utter sentences such as **“the United States should do . . . ”** or **“the American people want . . . ”** or **“China’s government ought to do . . . ,”** the better we will understand government, business, and all other forms of organization.


When addressing politics, we must accustom ourselves to think and speak about the actions and
interests of specific, named leaders rather than thinking and talking about fuzzy ideas like the
national interest, the common good, and the general welfare.

Once we think about what helps leaders come to and stay in power, we will also begin to see how to fix politics.
Politics, like all of life, is about individuals, each motivated to do what is good for them, not what is good for others.


* Rules to Rule By

What remarkable puzzles politics provides. Every day’s headlines shock and surprise us. Daily we
hear of frauds, chicanery, and double-dealing by corporate executives, new lies, thefts, cruelties
and even murders perpetrated by government leaders. 
We cannot help but wonder what flaws of culture, religion, upbringing, or historical circumstance explain the rise of these malevolent
despots, greedy Wall Street bankers, and unctuous oil barons. 

Is it true, as Shakespeare’s Cassius said, that the fault lies not in the stars but in ourselves? Or, more particularly, in those who lead us?
Most of us are content to believe that. And yet the truth is far different. 

Too often we accept the accounts of historians, journalists, pundits, and poets without probing
beneath the surface to discover deeper truths that point neither to the stars nor to ourselves. The
world of politics is dictated by rules.
Short is the term of any ruler foolish enough to govern without submitting to these rules to rule by. 

* The simplistic explanation 

Journalists, authors, and academics have endeavored to explain politics through storytelling.
They’ll explore why this or that leader seized power, or how the population of a far-flung country came to
revolt against their government, or why a specific policy enacted last year has reversed the
fortunes of millions of lives. 
And in the explanations of these cases, a journalist or historian can usually tell us what happened, and to whom, and maybe even why.

But beneath the particulars of the many political stories and histories we read are a few questions that seem to emerge time after
time, some profound, some seemingly minor, but all nagging and enduring in the back of our
minds: 

**How do tyrants hold on to power for so long?**
For that matter, **why is the tenure of
successful democratic leaders so brief?**

**How can countries with such misguided and corrupt
economic policies survive for so long?** 

**Why are countries that are prone to natural disasters so
often unprepared when they happen?** 

**And how can lands rich with natural resources at the same
time support populations stricken with poverty?**


Equally, we may well wonder: Why are Wall Street executives so politically tone-deaf that they dole
out billions in bonuses while plunging the global economy into recession? Why is the leadership of
a corporation, on whose shoulders so much responsibility rests, decided by so few people? Why are
failed CEOs retained and paid handsomely even as their company’s shareholders lose their shirts? 
In one form or another, these questions of political behavior pop up again and again. Each
explanation, each story, treats the errant leader and his or her faulty decision making as a one-off,
one-of-a-kind situation. But there is nothing unique about political behavior. 


These stories of the horrible things politicians or business executives do are appealing in their own
perverse way because they free us to believe we would behave differently if given the opportunity.
They liberate us to cast blame on the flawed person who somehow, inexplicably, had the authority
to make monumental—and monumentally bad—decisions. We are confident that we would never
act like Libya’s Muammar Qaddafi who bombed his own people to keep himself in power. We look
at the huge losses suffered under Kenneth Lay’s leadership by Enron’s employees, retirees, and
shareholders and think we aren’t like Kenneth Lay. We look at each case and conclude they are
different, uncharacteristic anomalies. Yet they are held together by the logic of politics, the rules
ruling rulers. 


The pundits of politics and the nabobs of news have left us ignorant of these rules. They are content to blame the doers of evil without inquiring why the worlds of politics and business seem
to succor miscreants or to turn good people into scoundrels. That’s why we are still asking the
same old questions. 

We’re still surprised by the prevalence of drought-induced food shortages in
Africa, 3,500 years after the pharaohs worked out how to store grain. We’re still shocked by the
devastation of earthquakes and tsunamis in places like Haiti, Iran, Myanmar, and Sri Lanka, and by
the seemingly lesser intensity of such natural disasters in North America and Europe. We’re still
troubled by the friendly handshakes and winks exchanged between democratic leaders and the
tyrants that they somehow justify empowering. 
